# Movie Recommendation System

### Loading Libraries & Dataset

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv('assets/movies.csv')

In [7]:
data.info()
data.columns

<class 'pandas.DataFrame'>
RangeIndex: 63249 entries, 0 to 63248
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     63249 non-null  str
 1   title                  63249 non-null  str
 2   duration               61174 non-null  str
 3   mpa                    41227 non-null  str
 4   rating                 59181 non-null  float64
 5   votes                  59181 non-null  str
 6   méta_score             15533 non-null  float64
 7   description            60889 non-null  str
 8   movie_link             63249 non-null  str
 9   writers                62980 non-null  str
 10  directors              63198 non-null  str
 11  stars                  62905 non-null  str
 12  budget                 15359 non-null  str
 13  opening_weekend_gross  16837 non-null  str
 14  gross_worldwide        20722 non-null  str
 15  gross_us_canada        19544 non-null  str
 16  release_date           63249 non-null  str
 17  countries_origin       63150 non-null  str
 18  filming_locations      46395 non-null  str
 19  production_companies   61276 non-null  str
 20  awards_content         0 non-null      float64
 21  genres                 62462 non-null  str
 22  languages              62919 non-null  str
dtypes: float64(3), str(20)
memory usage: 11.1 MB

Index(['id', 'title', 'duration', 'mpa', 'rating', 'votes', 'méta_score',
       'description', 'movie_link', 'writers', 'directors', 'stars', 'budget',
       'opening_weekend_gross', 'gross_worldwide', 'gross_us_canada',
       'release_date', 'countries_origin', 'filming_locations',
       'production_companies', 'awards_content', 'genres', 'languages'],
      dtype='str')

In [8]:
data.head()

,id,title,duration,mpa,rating,votes,méta_score,description,movie_link,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,filming_locations,production_companies,awards_content,genres,languages
0,tt0080125,West Indies,1h 50m,NaN,7.1,301,NaN,This vast musical fresco covers hundreds of ye...,https://www.imdb.com/title/tt0080125/,"['Daniel Boukman', 'Med Hondo']",...,NaN,NaN,NaN,1985-03-18,"['France', 'Algeria', 'Mauritania']",NaN,"['Les Films Soleil O', 'Office National de Cin...",NaN,"['Drama', 'Musical']",['French']
1,tt0249500,Estafa de amor,1h 33m,NaN,6.7,14,NaN,NaN,https://www.imdb.com/title/tt0249500/,"['Caridad Bravo Adams', 'Miguel M. Delgado', '...",...,NaN,NaN,NaN,1956-09-27,['Mexico'],NaN,['Filmadora Chapultepec'],NaN,['Drama'],['Spanish']
2,tt0054151,Brother,1h 38m,NaN,6.9,498,NaN,Set in 1926 when Japanese tradition was much s...,https://www.imdb.com/title/tt0054151/,"['Aya Kôda', 'Yôko Mizuki']",...,NaN,NaN,NaN,1960-11-01,['Japan'],NaN,['Daiei'],NaN,['Drama'],['Japanese']
3,tt6136430,Ferrante Fever,1h 14m,NaN,6.3,196,52.0,"Hillary Clinton, Roberto Saviano, Jonathan Fra...",https://www.imdb.com/title/tt6136430/,"['Laura Buffoni', 'Giacomo Durzi']",...,"$3,509","$14,518","$11,137",2019-03-08,"['Italy', 'France']","['Manhattan, New York City, New York, USA']","['Malìa', 'Rai Cinema', 'QMI']",NaN,['Documentary'],"['Italian', 'French', 'English']"
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,1h 44m,R,7.1,8.3K,61.0,Tanjiro undergoes rigorous training with the S...,https://www.imdb.com/title/tt30395619/,['Koyoharu Gotouge'],...,"$11,505,414","$44,354,825","$17,657,658",2024-02-23,['Japan'],NaN,"['Shueisha', 'Aniplex', 'Ufotable']",NaN,"['Anime', 'Dark Fantasy', 'Shōnen', 'Supernatu...",['Japanese']

### Trimming down to important columns

In [9]:
data = data[
    [
        'id', 
        'title',
        'release_date',
        'rating',
        'description',
        'writers', 
        'directors', 
        'stars', 
        'genres' 
    ]
]
data.head()

,id,title,release_date,rating,description,writers,directors,stars,genres
0,tt0080125,West Indies,1985-03-18,7.1,This vast musical fresco covers hundreds of ye...,"['Daniel Boukman', 'Med Hondo']",['Med Hondo'],"['Cyril Aventurin', 'Fernand Berset', 'Roland ...","['Drama', 'Musical']"
1,tt0249500,Estafa de amor,1956-09-27,6.7,NaN,"['Caridad Bravo Adams', 'Miguel M. Delgado', '...",['Miguel M. Delgado'],"['Elsa Aguirre', 'Ramón Gay', 'Carmen Montejo'...",['Drama']
2,tt0054151,Brother,1960-11-01,6.9,Set in 1926 when Japanese tradition was much s...,"['Aya Kôda', 'Yôko Mizuki']",['Kon Ichikawa'],"['Keiko Kishi', 'Hiroshi Kawaguchi', 'Kinuyo T...",['Drama']
3,tt6136430,Ferrante Fever,2019-03-08,6.3,"Hillary Clinton, Roberto Saviano, Jonathan Fra...","['Laura Buffoni', 'Giacomo Durzi']",['Giacomo Durzi'],"['Roberto Faenza', 'Jonathan Franzen', 'Ann Go...",['Documentary']
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,2024-02-23,7.1,Tanjiro undergoes rigorous training with the S...,['Koyoharu Gotouge'],['Haruo Sotozaki'],"['Natsuki Hanae', 'Kengo Kawanishi', 'Akari Ki...","['Anime', 'Dark Fantasy', 'Shōnen', 'Supernatu..."

### Dropping null values

In [20]:
data = data[data['description'].notna()]
data = data[data['writers'].notna()]
data = data[data['stars'].notna()]
data = data[data['genres'].notna()]
data = data[data['directors'].notna()]
data.info()

<class 'pandas.DataFrame'>
Index: 57423 entries, 0 to 63248
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            57423 non-null  str
 1   title         57423 non-null  str
 2   release_date  57423 non-null  str
 3   rating        57423 non-null  float64
 4   description   57423 non-null  str
 5   writers       57423 non-null  str
 6   directors     57423 non-null  str
 7   stars         57423 non-null  str
 8   genres        57423 non-null  str
dtypes: float64(1), str(8)
memory usage: 4.4 MB

In [21]:
data["rating"] = data["rating"].fillna(0)
data.head()

,id,title,release_date,rating,description,writers,directors,stars,genres
0,tt0080125,West Indies,1985-03-18,7.1,This vast musical fresco covers hundreds of ye...,"['Daniel Boukman', 'Med Hondo']",['Med Hondo'],"['Cyril Aventurin', 'Fernand Berset', 'Roland ...","['Drama', 'Musical']"
2,tt0054151,Brother,1960-11-01,6.9,Set in 1926 when Japanese tradition was much s...,"['Aya Kôda', 'Yôko Mizuki']",['Kon Ichikawa'],"['Keiko Kishi', 'Hiroshi Kawaguchi', 'Kinuyo T...",['Drama']
3,tt6136430,Ferrante Fever,2019-03-08,6.3,"Hillary Clinton, Roberto Saviano, Jonathan Fra...","['Laura Buffoni', 'Giacomo Durzi']",['Giacomo Durzi'],"['Roberto Faenza', 'Jonathan Franzen', 'Ann Go...",['Documentary']
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,2024-02-23,7.1,Tanjiro undergoes rigorous training with the S...,['Koyoharu Gotouge'],['Haruo Sotozaki'],"['Natsuki Hanae', 'Kengo Kawanishi', 'Akari Ki...","['Anime', 'Dark Fantasy', 'Shōnen', 'Supernatu..."
5,tt1633359,The Toxic Avenger,2025-08-29,6.0,A horrible toxic accident transforms downtrodd...,"['Macon Blair', 'Lloyd Kaufman', 'Joe Ritter']",['Macon Blair'],"['Julian Kostov', 'Kevin Bacon', 'Peter Dinkla...","['B-Horror', 'Splatter Horror', 'Action', 'Com..."

### Tag prepration

In [22]:
def to_list(x):
    import ast
    return ast.literal_eval(x)[:7]

def description_to_list(x):
    return [i for i in x.split(' ')]

def title_to_list(x):
    return [i for i in x.split(' ')]

def limiter(x):
    return x[:7]

In [23]:
# List Conversion
data['writers'] = data['writers'].apply(to_list)
data['directors'] = data['directors'].apply(to_list)
data['stars'] = data['stars'].apply(to_list)
data['genres'] = data['genres'].apply(to_list)

data['description'] = data['description'].apply(description_to_list)
data['title_for_tag'] = data['title'].apply(title_to_list)

data.head()

,id,title,release_date,rating,description,writers,directors,stars,genres,title_for_tag
0,tt0080125,West Indies,1985-03-18,7.1,"[This, vast, musical, fresco, covers, hundreds...","[Daniel Boukman, Med Hondo]",[Med Hondo],"[Cyril Aventurin, Fernand Berset, Roland Berti...","[Drama, Musical]","[West, Indies]"
2,tt0054151,Brother,1960-11-01,6.9,"[Set, in, 1926, when, Japanese, tradition, was...","[Aya Kôda, Yôko Mizuki]",[Kon Ichikawa],"[Keiko Kishi, Hiroshi Kawaguchi, Kinuyo Tanaka...",[Drama],[Brother]
3,tt6136430,Ferrante Fever,2019-03-08,6.3,"[Hillary, Clinton,, Roberto, Saviano,, Jonatha...","[Laura Buffoni, Giacomo Durzi]",[Giacomo Durzi],"[Roberto Faenza, Jonathan Franzen, Ann Goldste...",[Documentary],"[Ferrante, Fever]"
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,2024-02-23,7.1,"[Tanjiro, undergoes, rigorous, training, with,...",[Koyoharu Gotouge],[Haruo Sotozaki],"[Natsuki Hanae, Kengo Kawanishi, Akari Kitô, Y...","[Anime, Dark Fantasy, Shōnen, Supernatural Fan...","[Demon, Slayer:, Kimetsu, No, Yaiba, -, To, th..."
5,tt1633359,The Toxic Avenger,2025-08-29,6.0,"[A, horrible, toxic, accident, transforms, dow...","[Macon Blair, Lloyd Kaufman, Joe Ritter]",[Macon Blair],"[Julian Kostov, Kevin Bacon, Peter Dinklage, E...","[B-Horror, Splatter Horror, Action, Comedy, Ho...","[The, Toxic, Avenger]"

In [25]:
data['tag'] = data['title_for_tag'] + data['description'] + data['writers'] + data['directors'] + data['stars'] + data['genres']
data["tag"] = data["tag"].apply(lambda x: " ".join(x).lower())
data = data[["id", "title","release_date", "rating", "tag"]]
data.head()

,id,title,release_date,rating,tag
0,tt0080125,West Indies,1985-03-18,7.1,west indies this vast musical fresco covers hu...
2,tt0054151,Brother,1960-11-01,6.9,brother set in 1926 when japanese tradition wa...
3,tt6136430,Ferrante Fever,2019-03-08,6.3,"ferrante fever hillary clinton, roberto savian..."
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,2024-02-23,7.1,demon slayer: kimetsu no yaiba - to the hashir...
5,tt1633359,The Toxic Avenger,2025-08-29,6.0,the toxic avenger a horrible toxic accident tr...

### Stemming the tag

In [26]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem(text):
    y = [ps.stem(i) for i in text.split()]
    return " ".join(y)

In [27]:
data['tag'] = data['tag'].apply(stem)

In [28]:
data.head()

,id,title,release_date,rating,tag
0,tt0080125,West Indies,1985-03-18,7.1,west indi thi vast music fresco cover hundr of...
2,tt0054151,Brother,1960-11-01,6.9,brother set in 1926 when japanes tradit wa muc...
3,tt6136430,Ferrante Fever,2019-03-08,6.3,"ferrant fever hillari clinton, roberto saviano..."
4,tt30395619,Demon Slayer: Kimetsu No Yaiba - To the Hashir...,2024-02-23,7.1,demon slayer: kimetsu no yaiba - to the hashir...
5,tt1633359,The Toxic Avenger,2025-08-29,6.0,the toxic aveng a horribl toxic accid transfor...

### Vectorizing with TF-IDF

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=15000, stop_words='english', ngram_range=(1,2))
vector = tfidf.fit_transform(data['tag'])

### Setting up Near Neighbour

In [30]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(n_neighbors=6, metric='cosine', algorithm='brute')
model.fit(vector)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [65]:
position = data[data["title"] == "Transformers: Age of Extinction"]

if position.empty:
    print("Position not found")
else:
    iloc_index = data.index.get_loc(position.index[0])
    iloc_index

In [66]:
_, indices = model.kneighbors(vector[iloc_index], n_neighbors=6)
for i in indices[0][1:]:
    print(data.iloc[i]["title"])

Transformers: The Last Knight
The Impostors
Big Night
Final Portrait
Slipstream

### Saving the Dataset, Vector and Model

Run the below code to save the dataset, vector and model\
It can then be used to further consumend as API

In [67]:
import pickle

with open('assets/vector.pkl', 'wb') as f:
    pickle.dump(vector, f)

with open('assets/model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('assets/data.pkl', 'wb') as f:
    pickle.dump(data, f)

In [68]:
with open('assets/vector.pkl', 'rb') as f:
    vector = pickle.load(f)
with open('assets/model.pkl', 'rb') as f:
    model = pickle.load(f)
with open('assets/data.pkl', 'rb') as f:
    data = pickle.load(f)